version: "3.0"
services:
  postgres:
    restart: always
    image: postgres:14.1-alpine
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=somebase2
    #command: 'run -d -p 5432:5432 postgres postgres -h 0.0.0.0'
    networks:
      - custom
networks:
  custom:
    driver: bridge
